apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  labels:
    app: bms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms-app
  template:
    metadata:
      labels:
        app: bms-app
    spec:
      containers:
      - name: bms-app
        image: vaibhavbansal26/bms-prime:latest
        ports:
        - containerPort: 3000
